### ISSUE TITLE
Update Docker image names to use the new repository

### ISSUE THREAD

**Issue by bradmccoydev** [kubeshop/testkube-executor-keptn#2]
Replace every occurrence of (docker) image names and tags from `keptnsandbox/keptn-service-template-go` to your docker organization and image name (e.g., `kubeshop/testkube-executor-keptn`)

This can be as simple as using vs code and going find keptnsandbox/keptn-service-template-go

And then have a look and replace them with kubeshop/testkube-executor-keptn go through each file and look closely dont replace all

Remember to follow the contributing guidelines here: https://github.com/bradmccoydev/mentoring/blob/main/CONTRIBUTING.md
If you don't follow these practices then your PR will be rejected.

Docker Registry: https://hub.docker.com/repository/docker/kubeshop/testkube-executor-keptn

**Comment by vrukshaliii** [comment]
@bradmccoydev  Can I work on this issue?

**Comment by kingsathurthi** [comment]
@Vrukshali-26 I already completed
